//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_mcs_Ajax.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MCSEntities : DbContext
    {
        public MCSEntities()
            : base("name=MCSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<newEquipment> newEquipments { get; set; }
        public virtual DbSet<TablesManufacturer> TablesManufacturers { get; set; }
        public virtual DbSet<TablesModel> TablesModels { get; set; }
        public virtual DbSet<TrackMeter> TrackMeters { get; set; }
        public virtual DbSet<TrackServiceHistory> TrackServiceHistories { get; set; }
        public virtual DbSet<TrackServiceHistoryPart> TrackServiceHistoryParts { get; set; }
        public virtual DbSet<TrackServiceHistoryProvider> TrackServiceHistoryProviders { get; set; }
    }
}
