//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_mcs_Ajax.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MCSEntities : DbContext
    {
        public MCSEntities()
            : base("name=MCSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<newEquipment> newEquipments { get; set; }
        public virtual DbSet<TablesManufacturer> TablesManufacturers { get; set; }
        public virtual DbSet<TablesModel> TablesModels { get; set; }
        public virtual DbSet<TrackMeter> TrackMeters { get; set; }
        public virtual DbSet<TrackServiceHistory> TrackServiceHistories { get; set; }
        public virtual DbSet<TrackServiceHistoryPart> TrackServiceHistoryParts { get; set; }
        public virtual DbSet<TrackServiceHistoryProvider> TrackServiceHistoryProviders { get; set; }
    }
}
