//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_mcs_Ajax.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackServiceHistoryPart
    {
        public int intServiceHistoryPartsId { get; set; }
        public Nullable<int> intServiceHistoryId { get; set; }
        public int intMasterPartId { get; set; }
        public Nullable<double> quantity { get; set; }
        public Nullable<double> unit_cost { get; set; }
        public string old_job_no { get; set; }
        public Nullable<int> intUnitCostCurrency { get; set; }
    }
}
