//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_mcs_Ajax.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackServiceHistoryPart
    {
        public int intServiceHistoryPartsId { get; set; }
        public Nullable<int> intServiceHistoryId { get; set; }
        public int intMasterPartId { get; set; }
        public Nullable<double> quantity { get; set; }
        public Nullable<double> unit_cost { get; set; }
        public string old_job_no { get; set; }
        public Nullable<int> intUnitCostCurrency { get; set; }
    
        public virtual TrackServiceHistory TrackServiceHistory { get; set; }
    }
}
