//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_mcs_Ajax.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackServiceHistory
    {
        public int intServiceHistoryId { get; set; }
        public Nullable<int> intEquipmentID { get; set; }
        public Nullable<int> intComponentId { get; set; }
        public System.DateTime dRepairDate { get; set; }
        public Nullable<int> intStopReason { get; set; }
        public string strDescriptionProblem { get; set; }
        public Nullable<double> intMeterDue { get; set; }
        public Nullable<int> intPmChecklist { get; set; }
        public Nullable<int> intSMCSJob { get; set; }
        public string strSMCSJob { get; set; }
        public Nullable<int> intSMCSComponentID { get; set; }
        public string strSMCSComponentID { get; set; }
        public Nullable<int> intModifierId { get; set; }
        public Nullable<int> intQuantityId { get; set; }
        public Nullable<int> intJobReasonId { get; set; }
        public double intlLaborHours { get; set; }
        public string repair_waiting_on { get; set; }
        public string strDescriptiontFindings { get; set; }
        public string old_job_no { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> intRegNo { get; set; }
        public Nullable<int> intSegment { get; set; }
        public Nullable<int> intCountSegment { get; set; }
        public Nullable<int> intLocationId { get; set; }
        public string intNumberAlong { get; set; }
        public Nullable<int> intEvalutionId { get; set; }
        public Nullable<double> floatMtbsAfterPm { get; set; }
        public Nullable<int> intMtbsAfterPmServiceId { get; set; }
    
        public virtual newEquipment newEquipment { get; set; }
    }
}
