//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_mcs_Ajax.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackServiceHistoryProvider
    {
        public int intServiceHistoryProviderID { get; set; }
        public int intSupplierId { get; set; }
        public Nullable<double> intRepairLabor { get; set; }
        public Nullable<double> intLaborRate { get; set; }
        public Nullable<int> intServiceHistoryId { get; set; }
        public string old_job_no { get; set; }
    }
}
