//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_mcs_Ajax.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackMeter
    {
        public int intMeteredId { get; set; }
        public int intEquipmentID { get; set; }
        public System.DateTime dMeterDate { get; set; }
        public double intMeterReading { get; set; }
        public Nullable<double> intHoursHoursOperation { get; set; }
        public Nullable<double> intTotalMeter { get; set; }
        public bool boolMeterReplaced { get; set; }
        public int intTypeMetered { get; set; }
        public Nullable<int> intComponentId { get; set; }
        public Nullable<int> intLocationId { get; set; }
    
        public virtual newEquipment newEquipment { get; set; }
    }
}
