//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_mcs_Ajax.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackServiceHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrackServiceHistory()
        {
            this.TrackServiceHistoryProviders = new HashSet<TrackServiceHistoryProvider>();
            this.TrackServiceHistoryParts = new HashSet<TrackServiceHistoryPart>();
        }
    
        public int intServiceHistoryId { get; set; }
        public Nullable<int> intEquipmentID { get; set; }
        public Nullable<int> intComponentId { get; set; }
        public System.DateTime dRepairDate { get; set; }
        public Nullable<int> intStopReason { get; set; }
        public string strDescriptionProblem { get; set; }
        public Nullable<double> intMeterDue { get; set; }
        public Nullable<int> intPmChecklist { get; set; }
        public Nullable<int> intSMCSJob { get; set; }
        public string strSMCSJob { get; set; }
        public Nullable<int> intSMCSComponentID { get; set; }
        public string strSMCSComponentID { get; set; }
        public Nullable<int> intModifierId { get; set; }
        public Nullable<int> intQuantityId { get; set; }
        public Nullable<int> intJobReasonId { get; set; }
        public double intlLaborHours { get; set; }
        public string repair_waiting_on { get; set; }
        public string strDescriptiontFindings { get; set; }
        public string old_job_no { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> intRegNo { get; set; }
        public Nullable<int> intSegment { get; set; }
        public Nullable<int> intCountSegment { get; set; }
        public Nullable<int> intLocationId { get; set; }
        public string intNumberAlong { get; set; }
        public Nullable<int> intEvalutionId { get; set; }
        public Nullable<double> floatMtbsAfterPm { get; set; }
        public Nullable<int> intMtbsAfterPmServiceId { get; set; }
    
        public virtual newEquipment newEquipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrackServiceHistoryProvider> TrackServiceHistoryProviders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrackServiceHistoryPart> TrackServiceHistoryParts { get; set; }
    }
}
