//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_mcs_Ajax.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackServiceHistoryProvider
    {
        public int intServiceHistoryProviderID { get; set; }
        public int intSupplierId { get; set; }
        public Nullable<double> intRepairLabor { get; set; }
        public Nullable<double> intLaborRate { get; set; }
        public Nullable<int> intServiceHistoryId { get; set; }
        public string old_job_no { get; set; }
    }
}
